# Generated by Django 5.2.2 on 2025-11-17 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_description', models.CharField(max_length=500, unique=True)),
                ('analysis_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_analysis_cache',
                'indexes': [models.Index(fields=['meal_description'], name='ai_analysis_meal_de_29ae35_idx'), models.Index(fields=['expires_at'], name='ai_analysis_expires_40f282_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('notifications', models.BooleanField(default=True)),
                ('units', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=10)),
                ('reminder_time', models.TimeField(blank=True, help_text='Daily reminder time', null=True)),
                ('weekly_goal', models.PositiveIntegerField(default=7, help_text='Weekly workout goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, help_text='Protein in grams', null=True)),
                ('carbs', models.FloatField(blank=True, help_text='Carbs in grams', null=True)),
                ('fats', models.FloatField(blank=True, help_text='Fats in grams', null=True)),
                ('portion_size', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('meal', 'Meal'), ('workout', 'Workout'), ('reminder', 'Reminder'), ('appointment', 'Appointment')], max_length=20)),
                ('datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule_items',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('activity_level', models.PositiveIntegerField(default=3, help_text='Activity level from 1 (sedentary) to 5 (very active)')),
                ('daily_calorie_goal', models.PositiveIntegerField(default=2000)),
                ('dietary_preferences', models.TextField(blank=True, help_text='Comma-separated dietary preferences')),
                ('allergies', models.TextField(blank=True, help_text='Comma-separated allergies')),
                ('medical_conditions', models.TextField(blank=True, help_text='Comma-separated medical conditions')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
